/// data.js

// How many shards you currently own for the *initial* tracked Sinner.
export const initialShardsOwned = 0;

// Default target shards for each Sinner (used if no goals are set yet)
export const defaultTargetShards = 400;

// Game constants
export const avgShardsPerBox = 2;   // 1–3 shards → average of 2
export const boxesPerRun = 9;       // 9 yellow boxes per MD run
export const weeklyBonusBoxes = 63; // 3 bonuses cashed at once

// Costs
export const costPer000 = 400; // one 000 ID or EGO set
export const costPer00 = 150;  // one 00 ID

// Base Sinners (shared with randomiser)
export const sinners = [
  { id: "yi-sang",   name: "Yi Sang" },
  { id: "faust",     name: "Faust" },
  { id: "don-quixote", name: "Don Quixote" },
  { id: "ryoshu",    name: "Ryōshū" },
  { id: "meursault", name: "Meursault" },
  { id: "hong-lu",   name: "Hong Lu" },
  { id: "heathcliff", name: "Heathcliff" },
  { id: "ishmael",   name: "Ishmael" },
  { id: "rodion",    name: "Rodion" },
  { id: "sinclair",  name: "Sinclair" },
  { id: "outis",     name: "Outis" },
  { id: "gregor",    name: "Gregor" },
];

// Convenience exports for existing calculator code
export const sinnerNames = sinners.map((s) => s.name);

// Map display name ↔ slug (for linking UI ↔ IDs/EGOs later)
export const sinnerSlugByName = Object.fromEntries(
  sinners.map((s) => [s.name, s.id])
);
export const sinnerNameBySlug = Object.fromEntries(
  sinners.map((s) => [s.id, s.name])
);

// Which Sinner the calculator tracks by default
export const defaultActiveSinner = "Yi Sang";

// --- Identities per Sinner ---
// Each entry also includes sinnerId for safety.
export const sinnerIdentities = {
  "yi-sang": [
    { id: "yi-sang-lcb", sinnerId: "yi-sang", name: "LCB Sinner", isBase: true, img: "img/IDs/yi-sang-lcb.png", keywords: ["sinking", "slash", "pierce"], rarity: "base", },
    { id: "yi-sang-seven", sinnerId: "yi-sang", name: "Seven Assoc. South Section 6", img: "img/IDs/yi-sang-seven.png", keywords: ["rupture", "pierce", "blunt"], rarity: "00"},
    { id: "yi-sang-molar", sinnerId: "yi-sang", name: "Molar Officer Fixer", img: "img/IDs/yi-sang-molar.png", keywords: ["tremor", "pierce", "blunt"], rarity: "00"},
    { id: "yi-sang-pequod", sinnerId: "yi-sang", name: "The Pequod First Mate", img: "img/IDs/yi-sang-pequod.png", keywords: ["bleed", "poise", "pierce"], rarity: "00"},
    { id: "yi-sang-dieci", sinnerId: "yi-sang", name: "Dieci Assoc. South Section 4", img: "img/IDs/yi-sang-dieci.png", keywords: ["sinking", "blunt", "pierce"], rarity: "00"},
    { id: "yi-sang-lceego", sinnerId: "yi-sang", name: "LCE EGO: Lantern", img: "img/IDs/yi-sang-lceego.png", keywords: ["rupture", "blunt", "pierce"], rarity: "00"},
    { id: "yi-sang-blade", sinnerId: "yi-sang", name: "Blade Lineage Salsu", img: "img/IDs/yi-sang-blade.png", keywords: ["slash", "poise"], rarity: "000"},
    { id: "yi-sang-efflorescedego", sinnerId: "yi-sang", name: "Effloresced EGO: Spicebush", img: "img/IDs/yi-sang-efflorescedego.png", keywords: ["sinking", "tremor", "pierce", "blunt"], rarity: "000"},
    { id: "yi-sang-wcorp", sinnerId: "yi-sang", name: "W.Corp L3 Cleanup Agent", img: "img/IDs/yi-sang-wcorp.png", keywords: ["rupture", "charge", "slash", "pierce"], rarity: "000",},
    { id: "yi-sang-ring", sinnerId: "yi-sang", name: "The Ring Pointillist Student", img: "img/IDs/yi-sang-ring.png", keywords: ["bleed", "pierce"], rarity: "000",},
    { id: "yi-sang-lobotomyego", sinnerId: "yi-sang", name: "Lobotomy EGO: Solemn Lament", img: "img/IDs/yi-sang-lobotomyego.png", keywords: ["sinking", "pierce"], rarity: "000",},
    { id: "yi-sang-liu", sinnerId: "yi-sang", name: "Liu Assoc. South Section 3", img: "img/IDs/yi-sang-liu.png", keywords: ["burn", "slash"], rarity: "000",},
    { id: "yi-sang-ncorpego", sinnerId: "yi-sang", name: "N Corp EGO: Fell Bullet", img: "img/IDs/yi-sang-ncorpego.png", keywords: ["bleed", "poise", "blunt", "pierce"], rarity: "000",},
    { id: "yi-sang-heishou", sinnerId: "yi-sang", name: "Heishou Pack - Wu Branch Adept", img: "img/IDs/yi-sang-heishou.png", keywords: ["rupture", "tremor", "slash"], rarity: "000",},
    // Add new Yi Sang IDs here
  ],

  "faust": [
    { id: "faust-lcb", sinnerId: "faust", name: "LCB Sinner", isBase: true, img: "img/IDs/faust-lcb.png", keywords: ["blunt", "pierce"], rarity: "base",},
    { id: "faust-wcorp", sinnerId: "faust", name: "W Corp. L2 Cleanup Agent", img: "img/IDs/faust-wcorp.png", keywords: ["charge", "blunt"], rarity: "00",},
    { id: "faust-lobotomycorp", sinnerId: "faust", name: "Lobotomy Corp. Remnant", img: "img/IDs/faust-lobotomycorp.png", keywords: ["poise", "rupture", "slash", "pierce"], rarity: "00",},
    { id: "faust-zwei", sinnerId: "faust", name: "Zwei Assoc. South Section 4", img: "img/IDs/faust-zwei.png", keywords: ["pierce", "slash", ], rarity: "00",},
    { id: "faust-wuthering", sinnerId: "faust", name: "Wuthering Heights Butler", img: "img/IDs/faust-wuthering.png", keywords: ["sinking", "slash", "blunt", ], rarity: "00",},
    { id: "faust-ncorp", sinnerId: "faust", name: "The One Who Grips", img: "img/IDs/faust-ncorp.png", keywords: ["bleed", "pierce", "blunt", ], rarity: "000",},
    { id: "faust-seven", sinnerId: "faust", name: "Seven Assoc. South Section 4", img: "img/IDs/faust-seven.png", keywords: ["rupture", "slash", ], rarity: "000",},
    { id: "faust-lobotomyego", sinnerId: "faust", name: "Lobotomy EGO: Regret", img: "img/IDs/faust-lobotomyego.png", keywords: ["tremor", "blunt", ], rarity: "000",},
    { id: "faust-blade", sinnerId: "faust", name: "Blade Lineage Salsu", img: "img/IDs/faust-blade.png", keywords: ["bleed", "poise", "slash", "pierce", ], rarity: "000",},
    { id: "faust-multicrack", sinnerId: "faust", name: "MultiCrack Office Rep", img: "img/IDs/faust-multicrack.png", keywords: ["charge", "blunt", "slash", ], rarity: "000",},
    { id: "faust-lceego", sinnerId: "faust", name: "LCE EGO: Ardor Blossom Star", img: "img/IDs/faust-lceego.png", keywords: ["burn", "blunt", ], rarity: "000",},
    { id: "faust-heishou", sinnerId: "faust", name: "Heishou Pack - Mao Branch Adept", img: "img/IDs/faust-heishou.png", keywords: ["slash", "rupture", ], rarity: "000",},
    { id: "faust-shi", sinnerId: "faust", name: "Shi Assoc. East Section 3", img: "img/IDs/faust-shi.png", keywords: ["bleed", "slash", "poise", ], rarity: "000",},
    // Add new Faust IDs here
  ],

  "don-quixote": [
    { id: "don-quixote-lcb", sinnerId: "don-quixote", name: "LCB Sinner", isBase: true, img: "img/IDs/don-quixote-lcb.png", keywords: ["bleed", "pierce", ], rarity: "base",},
    { id: "don-quixote-shi", sinnerId: "don-quixote", name: "Shi Assoc. South Section 5 Director", img: "img/IDs/don-quixote-shi.png", keywords: ["poise", "slash", ], rarity: "00",},
    { id: "don-quixote-ncorp", sinnerId: "don-quixote", name: "N Corp. Mittelhammer", img: "img/IDs/don-quixote-ncorp.png", keywords: ["bleed", "tremor", "pierce", "blunt", ], rarity: "00",},
    { id: "don-quixote-lobotomyego-lantern", sinnerId: "don-quixote", name: "Lobotomy EGO: Lantern", img: "img/IDs/don-quixote-lobotomyegolantern.png", keywords: ["pierce", "slash", "rupture", ], rarity: "00",},
    { id: "don-quixote-blade", sinnerId: "don-quixote", name: "Blade Lineage Salsu", img: "img/IDs/don-quixote-blade.png", keywords: ["pierce", "slash", "poise", ], rarity: "00",},
    { id: "don-quixote-wcorp", sinnerId: "don-quixote", name: "W Corp. L3 Cleanup Agent", img: "img/IDs/don-quixote-wcorp.png", keywords: ["pierce", "slash", "rupture", "charge", ], rarity: "000",},
    { id: "don-quixote-cinq-south", sinnerId: "don-quixote", name: "Cinq Assoc. South Section 5 Director", img: "img/IDs/don-quixote-cinqsouth.png", keywords: ["pierce", ], rarity: "000",},
    { id: "don-quixote-middle", sinnerId: "don-quixote", name: "The Middle Little Sister", img: "img/IDs/don-quixote-middle.png", keywords: ["blunt", "bleed", ], rarity: "000",},
    { id: "don-quixote-tcorp", sinnerId: "don-quixote", name: "T.Corp. Class 3 Collection Staff", img: "img/IDs/don-quixote-tcorp.png", keywords: ["blunt", "slash", "tremor", ], rarity: "000",},
    { id: "don-quixote-bloodfiend", sinnerId: "don-quixote", name: "The Manager of La Manchaland", img: "img/IDs/don-quixote-bloodfiend.png", keywords: ["bleed", "pierce", ], rarity: "000",},
    { id: "don-quixote-cinq-east", sinnerId: "don-quixote", name: "Cinq Assoc. East Section 3", img: "img/IDs/don-quixote-cinqeast.png", keywords: ["burn", "poise", "pierce", ], rarity: "000",},
    { id: "don-quixote-lobotomyego-lovehate", sinnerId: "don-quixote", name: "Lobotomy EGO: In the Name of Love and Hate", img: "img/IDs/don-quixote-lobotomyegolovehate.png", keywords: ["sinking", "rupture", "charge", "blunt", ], rarity: "000",},
    { id: "don-quixote-heishou", sinnerId: "don-quixote", name: "Heishou Pack - Wei Branch", img: "img/IDs/don-quixote-heishou.png", keywords: ["sinking", "rupture", "blunt", ], rarity: "000",},
    // Add new Don IDs here
  ],

  "ryoshu": [
    { id: "ryoshu-lcb", sinnerId: "ryoshu", name: "LCB Sinner", isBase: true, img: "img/IDs/ryoshu-lcb.png", keywords: ["slash", "poise", ], rarity: "base",},
    { id: "ryoshu-seven", sinnerId: "ryoshu", name: "Seven Assoc. South Section 6", img: "img/IDs/ryoshu-seven.png", keywords: ["rupture", "blunt", "slash", ], rarity: "00",},
    { id: "ryoshu-lccb", sinnerId: "ryoshu", name: "LCCB Assistant Manager", img: "img/IDs/ryoshu-lccb.png", keywords: ["tremor", "rupture", "pierce", "blunt", ], rarity: "00",},
    { id: "ryoshu-liu", sinnerId: "ryoshu", name: "Liu Assoc. South Section 4", img: "img/IDs/ryoshu-liu.png", keywords: ["burn", "pierce", "slash", ], rarity: "00",},
    { id: "ryoshu-yurodivy", sinnerId: "ryoshu", name: "District 20 Yurodivy", img: "img/IDs/ryoshu-yurodivy.png", keywords: ["tremor", "blunt", "pierce", ], rarity: "00",},
    { id: "ryoshu-kurokumo", sinnerId: "ryoshu", name: "Kurokumo Clan Wakashu", img: "img/IDs/ryoshu-kurokumo.png", keywords: ["bleed", "pierce", ], rarity: "00",},
    { id: "ryoshu-chef", sinnerId: "ryoshu", name: "R.B. Chef de Cuisine", img: "img/IDs/ryoshu-chef.png", keywords: ["bleed", "pierce", "slash", ], rarity: "000",},
    { id: "ryoshu-wcorp", sinnerId: "ryoshu", name: "W Corp. L3 Cleanup Agent", img: "img/IDs/ryoshu-wcorp.png", keywords: ["slash", "charge", ], rarity: "000",},
    { id: "ryoshu-wuthering", sinnerId: "ryoshu", name: "Edgar Family Chief Butler", img: "img/IDs/ryoshu-wuthering.png", keywords: ["slash", "poise", ], rarity: "000",},
    { id: "ryoshu-lobotomyego", sinnerId: "ryoshu", name: "Lobotomy EGO: Red Eyes & Penitence", img: "img/IDs/ryoshu-lobotomyego.png", keywords: ["bleed", "blunt", ], rarity: "000",},
    { id: "ryoshu-heishou", sinnerId: "ryoshu", name: "Heishou Pack - Mao Branch", img: "img/IDs/ryoshu-heishou.png", keywords: ["rupture", "slash", ], rarity: "000",},
    { id: "ryoshu-ncorpego", sinnerId: "ryoshu", name: "N Corp. EGO: Contempt, Awe", img: "img/IDs/ryoshu-ncorpego.png", keywords: ["bleed", "tremor", "pierce", ], rarity: "000",},
    { id: "ryoshu-drifting", sinnerId: "ryoshu", name: "Drifting Blade of Hongyuan", img: "img/IDs/ryoshu-drifting.png", keywords: ["pierce", "poise", "rupture", ], rarity: "000",},
    // Add new Ryoshu IDs here
  ],

  "meursault": [
    { id: "meursault-lcb", sinnerId: "meursault", name: "LCB Sinner", isBase: true, img: "img/IDs/meursault-lcb.png", keywords: ["tremor", "blunt", ], rarity: "base",},
    { id: "meursault-liu", sinnerId: "meursault", name: "Liu Assoc. South Section 6", img: "img/IDs/meursault-liu.png", keywords: ["burn", "pierce", "blunt", ], rarity: "00",},
    { id: "meursault-rosespanner", sinnerId: "meursault", name: "Rosespanner Workshop Fixer", img: "img/IDs/meursault-rosespanner.png", keywords: ["tremor", "charge", "blunt", ], rarity: "00",},
    { id: "meursault-middle", sinnerId: "meursault", name: "The Middle Little Brother", img: "img/IDs/meursault-middle.png", keywords: ["bleed", "blunt", ], rarity: "00",},
    { id: "meursault-deadrabbit", sinnerId: "meursault", name: "Dead Rabbits Boss", img: "img/IDs/meursault-deadrabbit.png", keywords: ["rupture", "pierce", "blunt", ], rarity: "00",},
    { id: "meursault-wcorp", sinnerId: "meursault", name: "W Corp. L2 Cleanup Agent", img: "img/IDs/meursault-wcorp.png", keywords: ["rupture", "slash", "charge", ], rarity: "000",},
    { id: "meursault-ncorp", sinnerId: "meursault", name: "N Corp. Großhammer", img: "img/IDs/meursault-ncorp.png", keywords: ["bleed", "pierce", "blunt", ], rarity: "000",},
    { id: "meursault-rcorp", sinnerId: "meursault", name: "R Corp. 4th Pack Rhino", img: "img/IDs/meursault-rcorp.png", keywords: ["bleed", "blunt", "slash", "charge", ], rarity: "000",},
    { id: "meursault-blade", sinnerId: "meursault", name: "Blade Lineage Mentor", img: "img/IDs/meursault-blade.png", keywords: ["slash", "poise", ], rarity: "000",},
    { id: "meursault-dieci", sinnerId: "meursault", name: "Dieci Assoc. South Section 4 Director", img: "img/IDs/meursault-dieci.png", keywords: ["sinking", "blunt", "pierce", ], rarity: "000",},
    { id: "meursault-cinq", sinnerId: "meursault", name: "Cinq Assoc. West Section 3", img: "img/IDs/meursault-cinq.png", keywords: ["rupture", "pierce", "poise", ], rarity: "000",},
    { id: "meursault-thumb", sinnerId: "meursault", name: "The Thumb East Capo IIIII", img: "img/IDs/meursault-thumb.png", keywords: ["burn", "tremor", "blunt", "slash", ], rarity: "000",},
    { id: "meursault-bloodfiend", sinnerId: "meursault", name: "The Prince of La Manchaland", img: "img/IDs/meursault-bloodfiend.png", keywords: ["bleed", "rupture", "slash", ], rarity: "000",},
    // Add new Meursault IDs here
  ],

  "hong-lu": [
    { id: "hong-lu-lcb", sinnerId: "hong-lu", name: "LCB Sinner", isBase: true, img: "img/IDs/hong-lu-lcb.png", keywords: ["sinking", "rupture", "blunt", "slash", ], rarity: "base",},
    { id: "hong-lu-kurokumo", sinnerId: "hong-lu", name: "Kurokumo Clan Wakashu", img: "img/IDs/hong-lu-kurokumo.png", keywords: ["bleed", "slash", ], rarity: "00",},
    { id: "hong-lu-liu", sinnerId: "hong-lu", name: "Liu Assoc. South Section 5", img: "img/IDs/hong-lu-liu.png", keywords: ["burn", "blunt", ], rarity: "00",},
    { id: "hong-lu-wcorp", sinnerId: "hong-lu", name: "W Corp. L2 Cleanup Agent", img: "img/IDs/hong-lu-wcorp.png", keywords: ["rupture", "charge", "slash", "pierce", ], rarity: "00",},
    { id: "hong-lu-hookoffice", sinnerId: "hong-lu", name: "Hook Office Fixer", img: "img/IDs/hong-lu-hookoffice.png", keywords: ["bleed", "pierce", ], rarity: "00",},
    { id: "hong-lu-fanghuntoffice", sinnerId: "hong-lu", name: "Fanghunt Office Fixer", img: "img/IDs/hong-lu-fanghuntoffice.png", keywords: ["blunt", "rupture", ], rarity: "00",},
    { id: "hong-lu-tingtang", sinnerId: "hong-lu", name: "Tingtang Gang Gangleader", img: "img/IDs/hong-lu-tingtang.png", keywords: ["bleed", "pierce", "slash", ], rarity: "000",},
    { id: "hong-lu-kcorp", sinnerId: "hong-lu", name: "K Corp. Class 3 Excision Staff", img: "img/IDs/hong-lu-kcorp.png", keywords: ["rupture", "blunt", "slash", ], rarity: "000",},
    { id: "hong-lu-dieci", sinnerId: "hong-lu", name: "Dieci Assoc. South Section 4", img: "img/IDs/hong-lu-dieci.png", keywords: ["sinking", "blunt", "slash", ], rarity: "000",},
    { id: "hong-lu-yurodivy", sinnerId: "hong-lu", name: "District 20 Yurodivy", img: "img/IDs/hong-lu-yurodivy.png", keywords: ["tremor", "blunt", "pierce", ], rarity: "000",},
    { id: "hong-lu-fullstop", sinnerId: "hong-lu", name: "Full-Stop Office Rep", img: "img/IDs/hong-lu-fullstop.png", keywords: ["poise", "slash", "pierce", ], rarity: "000",},
    { id: "hong-lu-rcorp", sinnerId: "hong-lu", name: "R Corp. 4th Pack Reindeer", img: "img/IDs/hong-lu-rcorp.png", keywords: ["blunt", "sinking", "charge", ], rarity: "000",},
    { id: "hong-lu-heishou", sinnerId: "hong-lu", name: "The Lord of Hongyuan", img: "img/IDs/hong-lu-heishou.png", keywords: ["slash", "rupture", ], rarity: "000",},
    // Add new Hong Lu IDs here
  ],

  "heathcliff": [
    { id: "heathcliff-lcb", sinnerId: "heathcliff", name: "LCB Sinner", isBase: true, img: "img/IDs/heathcliff-lcb.png", keywords: ["tremor", "blunt", ], rarity: "base",},
    { id: "heathcliff-shi", sinnerId: "heathcliff", name: "Shi Assoc. South Section 5", img: "img/IDs/heathcliff-shi.png", keywords: ["poise", "pierce", "slash", ], rarity: "00",},
    { id: "heathcliff-ncorp", sinnerId: "heathcliff", name: "N Corp. Kleinhammer", img: "img/IDs/heathcliff-ncorp.png", keywords: ["bleed", "pierce", "blunt", ], rarity: "00",},
    { id: "heathcliff-seven", sinnerId: "heathcliff", name: "Seven Assoc. South Section 4", img: "img/IDs/heathcliff-seven.png", keywords: ["pierce", "slash", "rupture", ], rarity: "00",},
    { id: "heathcliff-multicrack", sinnerId: "heathcliff", name: "MultiCrack Office Fixer", img: "img/IDs/heathcliff-multicrack.png", keywords: ["blunt", "slash", "charge", ], rarity: "00",},
    { id: "heathcliff-rcorp", sinnerId: "heathcliff", name: "R Corp. 4th Pack Rabbit", img: "img/IDs/heathcliff-rcorp.png", keywords: ["bleed", "rupture", "charge", "pierce", ], rarity: "000",},
    { id: "heathcliff-lobotomyego", sinnerId: "heathcliff", name: "Lobotomy EGO: Sunshower", img: "img/IDs/heathcliff-lobotomyego.png", keywords: ["sinking", "rupture", "pierce", "blunt", ], rarity: "000",},
    { id: "heathcliff-pequod", sinnerId: "heathcliff", name: "The Pequod Harpooneer", img: "img/IDs/heathcliff-pequod.png", keywords: ["bleed", "poise", "pierce", ], rarity: "000",},
    { id: "heathcliff-oufi", sinnerId: "heathcliff", name: "Oufi Assoc. South Section 3", img: "img/IDs/heathcliff-oufi.png", keywords: ["tremor", "pierce", "slash", ], rarity: "000",},
    { id: "heathcliff-wuthering", sinnerId: "heathcliff", name: "Wild Hunt", img: "img/IDs/heathcliff-wuthering.png", keywords: ["sinking", "blunt", "slash", ], rarity: "000",},
    { id: "heathcliff-fullstop", sinnerId: "heathcliff", name: "Full-Stop Office Fixer", img: "img/IDs/heathcliff-fullstop.png", keywords: ["poise", "pierce", ], rarity: "000",},
    { id: "heathcliff-kurokumo", sinnerId: "heathcliff", name: "Kurokumo Clan Wakashu", img: "img/IDs/heathcliff-kurokumo.png", keywords: ["bleed", "slash", ], rarity: "000",},
    { id: "heathcliff-wcorp", sinnerId: "heathcliff", name: "W Corp. L4 Cleanup Agent", img: "img/IDs/heathcliff-wcorp.png", keywords: ["rupture", "charge", "blunt", ], rarity: "000",},
    { id: "heathcliff-heishou", sinnerId: "heathcliff", name: "Heishou Pack - You Branch Adept", img: "img/IDs/heathcliff-heishou.png", keywords: ["burn", "rupture", "slash", ], rarity: "000",},
    // Add new Heathcliff IDs here
  ],

  "ishmael": [
    { id: "ishmael-lcb", sinnerId: "ishmael", name: "LCB Sinner", isBase: true, img: "img/IDs/ishmael-lcb.png", keywords: ["tremor", "blunt", ], rarity: "base",},
    { id: "ishmael-shi", sinnerId: "ishmael", name: "Shi Assoc. South Section 5", img: "img/IDs/ishmael-shi.png", keywords: ["poise", "pierce", "slash", ], rarity: "00",},
    { id: "ishmael-lccb", sinnerId: "ishmael", name: "LCCB Assistant Manager", img: "img/IDs/ishmael-lccb.png", keywords: ["tremor", "rupture", "blunt", ], rarity: "00",},
    { id: "ishmael-lobotomyego", sinnerId: "ishmael", name: "Lobotomy EGO: Sloshing", img: "img/IDs/ishmael-lobotomyego.png", keywords: ["tremor", "rupture", "blunt", ], rarity: "00",},
    { id: "ishmael-wuthering", sinnerId: "ishmael", name: "Edgar Family Butler", img: "img/IDs/ishmael-wuthering.png", keywords: ["sinking", "poise", "blunt", "slash", ], rarity: "00",},
    { id: "ishmael-rcorp", sinnerId: "ishmael", name: "R Corp. 4th Pack Reindeer", img: "img/IDs/ishmael-rcorp.png", keywords: ["sinking", "charge", "blunt", ], rarity: "000",},
    { id: "ishmael-liu", sinnerId: "ishmael", name: "Liu Assoc. South Section 4", img: "img/IDs/ishmael-liu.png", keywords: ["burn", "blunt", ], rarity: "000",},
    { id: "ishmael-molar", sinnerId: "ishmael", name: "Molar Boatworks Fixer", img: "img/IDs/ishmael-molar.png", keywords: ["sinking", "tremor", "pierce", ], rarity: "000",},
    { id: "ishmael-pequod", sinnerId: "ishmael", name: "The Pequod Captain", img: "img/IDs/ishmael-pequod.png", keywords: ["bleed", "pierce", ], rarity: "000",},
    { id: "ishmael-zwei", sinnerId: "ishmael", name: "Zwei Assoc. West Section 3", img: "img/IDs/ishmael-zwei.png", keywords: ["tremor", "blunt", ], rarity: "000",},
    { id: "ishmael-kurokumo", sinnerId: "ishmael", name: "Kurokumo Clan Captain", img: "img/IDs/ishmael-kurokumo.png", keywords: ["bleed", "slash", ], rarity: "000",},
    { id: "ishmael-heishou", sinnerId: "ishmael", name: "Family Hierarch Candidate", img: "img/IDs/ishmael-heishou.png", keywords: ["rupture", "poise", "blunt", "slash", ], rarity: "000",},
    { id: "ishmael-jeongoffice", sinnerId: "ishmael", name: "Jeong's Office Rep", img: "img/IDs/ishmael-jeongoffice.png", keywords: ["tremor", "sinking", "slash", ], rarity: "000",},
    // Add new Ishmael IDs here
  ],

  "rodion": [
    { id: "rodion-lcb", sinnerId: "rodion", name: "LCB Sinner", isBase: true, img: "img/IDs/rodion-lcb.png", keywords: ["bleed", "slash", ], rarity: "base",},
    { id: "rodion-lccb", sinnerId: "rodion", name: "LCCB Assistant Manager", img: "img/IDs/rodion-lccb.png", keywords: ["blunt", ], rarity: "00",},
    { id: "rodion-ncorp", sinnerId: "rodion", name: "N Corp. Mittelhammer", img: "img/IDs/rodion-ncorp.png", keywords: ["bleed", "pierce", "blunt", ], rarity: "00",},
    { id: "rodion-zwei", sinnerId: "rodion", name: "Zwei Assoc. South Section 5", img: "img/IDs/rodion-zwei.png", keywords: ["blunt", "poise", ], rarity: "00",},
    { id: "rodion-tcorp", sinnerId: "rodion", name: "T Corp. Class 2 Collection Staff", img: "img/IDs/rodion-tcorp.png", keywords: ["tremor", "blunt", ], rarity: "00",},
    { id: "rodion-kurokumo", sinnerId: "rodion", name: "Kurokumo Clan Wakashu", img: "img/IDs/rodion-kurokumo.png", keywords: ["bleed", "poise", "slash", ], rarity: "000",},
    { id: "rodion-rosespanner", sinnerId: "rodion", name: "Rosespanner Workshop Rep", img: "img/IDs/rodion-rosespanner.png", keywords: ["tremor", "charge", "pierce", "blunt", ], rarity: "000",},
    { id: "rodion-dieci", sinnerId: "rodion", name: "Dieci Assoc. South Section 4", img: "img/IDs/rodion-dieci.png", keywords: ["blunt", "sinking", ], rarity: "000",},
    { id: "rodion-liu", sinnerId: "rodion", name: "Liu Assoc. South Section 4 Director", img: "img/IDs/rodion-liu.png", keywords: ["burn", "pierce", "blunt", ], rarity: "000",},
    { id: "rodion-devyat", sinnerId: "rodion", name: "Devyat' Assoc. North Section 3", img: "img/IDs/rodion-devyat.png", keywords: ["rupture", "slash", ], rarity: "000",},
    { id: "rodion-bloodfiend", sinnerId: "rodion", name: "The Princess of La Manchaland", img: "img/IDs/rodion-bloodfiend.png", keywords: ["bleed", "pierce", "rupture", ], rarity: "000",},
    { id: "rodion-heishou", sinnerId: "rodion", name: "Heishou Pack - Si Branch", img: "img/IDs/rodion-heishou.png", keywords: ["rupture", "poise", "pierce", "slash", ], rarity: "000",},
    { id: "rodion-lobotomyego", sinnerId: "rodion", name: "Lobotomy EGO: The Sword Sharpened with Tears", img: "img/IDs/rodion-lobotomyego.png", keywords: ["sinking", "pierce", ], rarity: "000",},
    // Add new Rodion IDs here
  ],

  "sinclair": [
    { id: "sinclair-lcb", sinnerId: "sinclair", name: "LCB Sinner", isBase: true, img: "img/IDs/sinclair-lcb.png", keywords: ["rupture", "slash", ], rarity: "base",},
    { id: "sinclair-zweisouth", sinnerId: "sinclair", name: "Zwei Assoc. South Section 6", img: "img/IDs/sinclair-zweisouth.png", keywords: ["tremor", "blunt",], rarity: "00",},
    { id: "sinclair-mariachi", sinnerId: "sinclair", name: "Los Mariachis Jefe", img: "img/IDs/sinclair-mariachi.png", keywords: ["sinking", "poise", "blunt",], rarity: "00",},
    { id: "sinclair-lobotomyego", sinnerId: "sinclair", name: "Lobotomy EGO: Red Sheet", img: "img/IDs/sinclair-lobotomyego.png", keywords: ["rupture", "pierce", "blunt",], rarity: "00",},
    { id: "sinclair-molar", sinnerId: "sinclair", name: "Molar Boatworks Fixer", img: "img/IDs/sinclair-molar.png", keywords: ["tremor", "pierce", "blunt",], rarity: "00",},
    { id: "sinclair-zweiwest", sinnerId: "sinclair", name: "Zwei Assoc. West Section 3", img: "img/IDs/sinclair-zweiwest.png", keywords: ["tremor", "blunt", "slash", ], rarity: "00",},
    { id: "sinclair-blade", sinnerId: "sinclair", name: "Blade Lineage Salsu", img: "img/IDs/sinclair-blade.png", keywords: ["bleed", "pierce", "slash", ], rarity: "000",},
    { id: "sinclair-ncorp", sinnerId: "sinclair", name: "The One Who Shall Grip", img: "img/IDs/sinclair-ncorp.png", keywords: ["burn", "bleed", "blunt", ], rarity: "000",},
    { id: "sinclair-cinq", sinnerId: "sinclair", name: "Cinq Assoc. South Section 4 Director", img: "img/IDs/sinclair-cinq.png", keywords: ["poise", "pierce", ], rarity: "000",},
    { id: "sinclair-dawnoffice", sinnerId: "sinclair", name: "Dawn Office Fixer", img: "img/IDs/sinclair-dawnoffice.png", keywords: ["burn", "pierce", "slash", ], rarity: "000",},
    { id: "sinclair-devyat", sinnerId: "sinclair", name: "Devyat' Assoc. North Section 3", img: "img/IDs/sinclair-devyat.png", keywords: ["rupture", "blunt", ], rarity: "000",},
    { id: "sinclair-middle", sinnerId: "sinclair", name: "The Middle Little Brother", img: "img/IDs/sinclair-middle.png", keywords: ["bleed", "blunt", ], rarity: "000",},
    { id: "sinclair-thumb", sinnerId: "sinclair", name: "The Thumb East Soldato II", img: "img/IDs/sinclair-thumb.png", keywords: ["burn", "bleed", "pierce", "slash", ], rarity: "000",},
    { id: "sinclair-heishou", sinnerId: "sinclair", name: "Heishou Pack - You Branch", img: "img/IDs/sinclair-heishou.png", keywords: ["burn", "rupture", "slash", ], rarity: "000",},
    // Add new Sinclair IDs here
  ],

  "outis": [
    { id: "outis-lcb", sinnerId: "outis", name: "LCB Sinner", isBase: true, img: "img/IDs/outis-lcb.png", keywords: ["rupture", "pierce", "slash", ], rarity: "base",},
    { id: "outis-blade", sinnerId: "outis", name: "Blade Lineage Salsu", img: "img/IDs/outis-blade.png", keywords: ["poise", "pierce", "slash", ], rarity: "00",},
    { id: "outis-gcorp", sinnerId: "outis", name: "G Corp. Head Manager", img: "img/IDs/outis-gcorp.png", keywords: ["sinking", "pierce", "blunt", ], rarity: "00",},
    { id: "outis-cinq", sinnerId: "outis", name: "Cinq Assoc. South Section 4", img: "img/IDs/outis-cinq.png", keywords: ["poise", "pierce", ], rarity: "00",},
    { id: "outis-ring", sinnerId: "outis", name: "The Ring Pointillist Student", img: "img/IDs/outis-ring.png", keywords: ["bleed", "pierce", ], rarity: "00",},
    { id: "outis-seven", sinnerId: "outis", name: "Seven Assoc. South Section 6 Director", img: "img/IDs/outis-seven.png", keywords: ["rupture", "blunt", "slash", ], rarity: "000",},
    { id: "outis-molar", sinnerId: "outis", name: "Molar Office Fixer", img: "img/IDs/outis-molar.png", keywords: ["tremor", "blunt", "slash", ], rarity: "000",},
    { id: "outis-lobotomyego", sinnerId: "outis", name: "Lobotomy EGO: Magic Bullet", img: "img/IDs/outis-lobotomyego.png", keywords: ["burn", "pierce", "blunt", ], rarity: "000",},
    { id: "outis-wuthering", sinnerId: "outis", name: "Wuthering Heights Chief Butler", img: "img/IDs/outis-wuthering.png", keywords: ["sinking", "blunt", ], rarity: "000",},
    { id: "outis-wcorp", sinnerId: "outis", name: "W Corp. L3 Cleanup Captain", img: "img/IDs/outis-wcorp.png", keywords: ["rupture", "charge", "blunt", "slash", ], rarity: "000",},
    { id: "outis-bloodfiend", sinnerId: "outis", name: "The Barber of La Manchaland", img: "img/IDs/outis-bloodfiend.png", keywords: ["bleed", "slash", ], rarity: "000",},
    { id: "outis-heishou", sinnerId: "outis", name: "Heishou Pack - Mao Branch", img: "img/IDs/outis-heishou.png", keywords: ["rupture", "slash", ], rarity: "000",},
    { id: "outis-tcorp", sinnerId: "outis", name: "T Corp. Class 3 VDCU Staff", img: "img/IDs/outis-tcorp.png", keywords: ["tremor", "blunt", ], rarity: "000",},
    // Add new Outis IDs here
  ],

  "gregor": [
    { id: "gregor-lcb", sinnerId: "gregor", name: "LCB Sinner", isBase: true, img: "img/IDs/gregor-lcb.png", keywords: ["rupture", "pierce", "slash", ], rarity: "base",},
    { id: "gregor-liu", sinnerId: "gregor", name: "Liu Assoc. South Section 6", img: "img/IDs/gregor-liu.png", keywords: ["burn", "blunt", ], rarity: "00",},
    { id: "gregor-chef", sinnerId: "gregor", name: "R.B. Sous-chef", img: "img/IDs/gregor-chef.png", keywords: ["bleed", "blunt", "slash", ], rarity: "00",},
    { id: "gregor-rosespanner", sinnerId: "gregor", name: "Rosespanner Workshop Fixer", img: "img/IDs/gregor-rosespanner.png", keywords: ["tremor", "rupture", "charge", "slash", "pierce", ], rarity: "00",},
    { id: "gregor-kurokumo", sinnerId: "gregor", name: "Kurokumo Clan Captain", img: "img/IDs/gregor-kurokumo.png", keywords: ["bleed", "blunt", "slash", ], rarity: "00",},
    { id: "gregor-gcorp", sinnerId: "gregor", name: "G Corp. Manager Corporal", img: "img/IDs/gregor-gcorp.png", keywords: ["rupture", "pierce", "slash", ], rarity: "000",},
    { id: "gregor-zwei", sinnerId: "gregor", name: "Zwei Assoc. South Section 4", img: "img/IDs/gregor-zwei.png", keywords: ["slash", ], rarity: "000",},
    { id: "gregor-twinhook", sinnerId: "gregor", name: "Twinhook Pirates First Mate", img: "img/IDs/gregor-twinhook.png", keywords: ["bleed", "poise", "pierce", ], rarity: "000",},
    { id: "gregor-wuthering", sinnerId: "gregor", name: "Edgar Family Heir", img: "img/IDs/gregor-wuthering.png", keywords: ["sinking", "slash", ], rarity: "000",},
    { id: "gregor-bloodfiend", sinnerId: "gregor", name: "The Priest of La Manchaland", img: "img/IDs/gregor-bloodfiend.png", keywords: ["bleed", "rupture", "blunt", ], rarity: "000",},
    { id: "gregor-firefist", sinnerId: "gregor", name: "Firefist Office Survivor", img: "img/IDs/gregor-firefist.png", keywords: ["burn", "blunt", ], rarity: "000",},
    { id: "gregor-heishou", sinnerId: "gregor", name: "Heishou Pack - Si Branch", img: "img/IDs/gregor-heishou.png", keywords: ["rupture", "poise", "pierce", "slash", ], rarity: "000",},
    { id: "gregor-nightawls", sinnerId: "gregor", name: "Night Awls Capitano", img: "img/IDs/gregor-nightawls.png", keywords: ["bleed", "tremor", "pierce", ], rarity: "000",},
    // Add new Gregor IDs here
  ]
};

// --- EGOs per Sinner ---
// rank: "ZAYIN" | "TETH" | "HE" | "WAW" | "ALEPH"
export const sinnerEgos = {
  "yi-sang": [
    {
      id: "yi-sang-crow-zayin",
      sinnerId: "yi-sang",
      name: "Crow's Eye View",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/yi-sang-crow-zayin.png",
      keywords: [],
      rarity: "EGO",
    },
    {
      id: "yi-sang-bygone-zayin",
      sinnerId: "yi-sang",
      name: "Bygone Days",
      rank: "ZAYIN",
      img: "img/EGOs/yi-sang-bygone-zayin.png",
      keywords: ["sinking", ],
      rarity: "EGO",
    },
    {
      id: "yi-sang-flame-teth",
      sinnerId: "yi-sang",
      name: "4th Match Flame",
      rank: "TETH",
      img: "img/EGOs/yi-sang-flame-teth.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "yi-sang-cairn-teth",
      sinnerId: "yi-sang",
      name: "Wishing Cairn",
      rank: "TETH",
      img: "img/EGOs/yi-sang-cairn-teth.png",
      keywords: [],
      rarity: "EGO",
    },
    {
      id: "yi-sang-dimension-he",
      sinnerId: "yi-sang",
      name: "Dimension Shredder",
      rank: "HE",
      img: "img/EGOs/yi-sang-dimension-he.png",
      keywords: ["rupture", "charge", ],
      rarity: "EGO",
    },
    {
      id: "yi-sang-fell-he",
      sinnerId: "yi-sang",
      name: "Fell Bullet",
      rank: "HE",
      img: "img/EGOs/yi-sang-fell-he.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    {
      id: "yi-sang-sunshower-waw",
      sinnerId: "yi-sang",
      name: "Sunshower",
      rank: "WAW",
      img: "img/EGOs/yi-sang-sunshower-waw.png",
      keywords: [],
      rarity: "EGO",
    },
  ],

  "faust": [
    {
      id: "faust-emitter-zayin",
      sinnerId: "faust",
      name: "Representation Emitter",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/faust-emitter-zayin.png",
      keywords: [],
      rarity: "EGO",
    },
    {
      id: "faust-hex-teth",
      sinnerId: "faust",
      name: "Hex Nail",
      rank: "TETH",
      img: "img/EGOs/faust-hex-teth.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    {
      id: "faust-9:2-teth",
      sinnerId: "faust",
      name: "9:2",
      rank: "TETH",
      img: "img/EGOs/faust-9-2-teth.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "faust-lasso-teth",
      sinnerId: "faust",
      name: "Lasso",
      rank: "TETH",
      img: "img/EGOs/faust-lasso-teth.png",
      keywords: ["rupture", ],
      rarity: "EGO",
    },
    {
      id: "faust-fluid-he",
      sinnerId: "faust",
      name: "Fluid Sac",
      rank: "HE",
      img: "img/EGOs/faust-fluid-he.png",
      rarity: "EGO",
    },
    {
      id: "faust-telepole-he",
      sinnerId: "faust",
      name: "Telepole",
      rank: "HE",
      img: "img/EGOs/faust-telepole-he.png",
      keywords: ["charge", ],
      rarity: "EGO",
    },
    {
      id: "faust-thoracalgia-he",
      sinnerId: "faust",
      name: "Thoracalgia",
      rank: "HE",
      img: "img/EGOs/faust-thoracalgia-he.png",
      keywords: ["poise", ],
      rarity: "EGO",
    },
    {
      id: "faust-meltdown-he",
      sinnerId: "faust",
      name: "Command: Meltdown",
      rank: "HE",
      img: "img/EGOs/faust-meltdown-he.png",
      keywords: ["burn", "rupture", ],
      rarity: "EGO",
    },
    {
      id: "faust-everlasting-waw",
      sinnerId: "faust",
      name: "Everlasting",
      rank: "WAW",
      img: "img/EGOs/faust-everlasting-waw.png",
      keywords: ["tremor", ],
      rarity: "EGO",
    },
    // Add new Faust EGOs here
  ],

  "don-quixote": [
    {
      id: "don-quixote-sancho-zayin",
      sinnerId: "don-quixote",
      name: "La Sangre de Sancho",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/don-quixote-sancho-zayin.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    {
      id: "don-quixote-stew-teth",
      sinnerId: "don-quixote",
      name: "Lifetime Stew",
      rank: "TETH",
      img: "img/EGOs/don-quixote-stew-teth.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "don-quixote-cairn-teth",
      sinnerId: "don-quixote",
      name: "Wishing Cairn",
      rank: "TETH",
      img: "img/EGOs/don-quixote-cairn-teth.png",
      keywords: ["bleed", "tremor", ],
      rarity: "EGO",
    },
    {
      id: "don-quixote-electric-teth",
      sinnerId: "don-quixote",
      name: "Electric Screaming",
      rank: "TETH",
      img: "img/EGOs/don-quixote-electric-teth.png",
      keywords: ["charge", ],
      rarity: "EGO",
    },
    {
      id: "don-quixote-fluid-he",
      sinnerId: "don-quixote",
      name: "Fluid Sac",
      rank: "HE",
      img: "img/EGOs/don-quixote-fluid-he.png",
      keywords: ["tremor", "sinking", ],
      rarity: "EGO",
    },
    {
      id: "don-quixote-telepole-he",
      sinnerId: "don-quixote",
      name: "Telepole",
      rank: "HE",
      img: "img/EGOs/don-quixote-telepole-he.png",
      keywords: ["charge", ],
      rarity: "EGO",
    },
    {
      id: "don-quixote-sheet-he",
      sinnerId: "don-quixote",
      name: "Red Sheet",
      rank: "HE",
      img: "img/EGOs/don-quixote-sheet-he.png",
      keywords: ["rupture", ],
      rarity: "EGO",
    },
    {
      id: "don-quixote-mircalla-waw",
      sinnerId: "don-quixote",
      name: "Yearning-Mircalla",
      rank: "WAW",
      img: "img/EGOs/don-quixote-mircalla-waw.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    {
      id: "don-quixote-lovehate-waw",
      sinnerId: "don-quixote",
      name: "In the Name of Love and Hate",
      rank: "WAW",
      img: "img/EGOs/don-quixote-lovehate-waw.png",
      keywords: ["rupture", "charge", ],
      rarity: "EGO",
    },
    // Add new Don EGOs here
  ],

  "ryoshu": [
    {
      id: "ryoshu-forest-zayin",
      sinnerId: "ryoshu",
      name: "Forest for the Flames",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/ryoshu-forest-zayin.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "ryoshu-soda-zayin",
      sinnerId: "ryoshu",
      name: "Soda",
      rank: "ZAYIN",
      img: "img/EGOs/ryoshu-soda-zayin.png",
      keywords: ["sinking", ],
      rarity: "EGO",
    },
    {
      id: "ryoshu-redeyes-teth",
      sinnerId: "ryoshu",
      name: "Red Eyes",
      rank: "TETH",
      img: "img/EGOs/ryoshu-redeyes-teth.png",
      rarity: "EGO",
    },
    {
      id: "ryoshu-obsession-teth",
      sinnerId: "ryoshu",
      name: "Blind Obsession",
      rank: "TETH",
      img: "img/EGOs/ryoshu-obsession-teth.png",
      keywords: ["poise", "charge", ],
      rarity: "EGO",
    },
    {
      id: "ryoshu-flame-he",
      sinnerId: "ryoshu",
      name: "4th Match Flame",
      rank: "HE",
      img: "img/EGOs/ryoshu-flame-he.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "ryoshu-redeyesopen-he",
      sinnerId: "ryoshu",
      name: "Red Eyes (Open)",
      rank: "HE",
      img: "img/EGOs/ryoshu-redeyesopen-he.png",
      rarity: "EGO",
    },
    {
      id: "ryoshu-thoracalgia-he",
      sinnerId: "ryoshu",
      name: "Thoracalgia",
      rank: "HE",
      img: "img/EGOs/ryoshu-thoracalgia-he.png",
      keywords: ["poise", ],
      rarity: "EGO",
    },
    {
      id: "ryoshu-contempt-waw",
      sinnerId: "ryoshu",
      name: "Contempt, Awe",
      rank: "WAW",
      img: "img/EGOs/ryoshu-contempt-waw.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    // Add new Ryoshu EGOs here
  ],

  "meursault": [
    {
      id: "meursault-chains-zayin",
      sinnerId: "meursault",
      name: "Chains of Others",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/meursault-chains-zayin.png",
      rarity: "EGO",
    },
    {
      id: "meursault-screwloose-teth",
      sinnerId: "meursault",
      name: "Screwloose Wallop",
      rank: "TETH",
      img: "img/EGOs/meursault-screwloose-teth.png",
      rarity: "EGO",
    },
    {
      id: "meursault-regret-teth",
      sinnerId: "meursault",
      name: "Regret",
      rank: "TETH",
      img: "img/EGOs/meursault-regret-teth.png",
      keywords: ["tremor", ],
      rarity: "EGO",
    },
    {
      id: "meursault-electric-teth",
      sinnerId: "meursault",
      name: "Electric Screaming",
      rank: "TETH",
      img: "img/EGOs/meursault-electric-teth.png",
      keywords: ["rupture", "charge", ],
      rarity: "EGO",
    },
    {
      id: "meursault-pursuance-he",
      sinnerId: "meursault",
      name: "Pursuance",
      rank: "HE",
      img: "img/EGOs/meursault-pursuance-he.png",
      keywords: ["tremor", ],
      rarity: "EGO",
    },
    {
      id: "meursault-capote-he",
      sinnerId: "meursault",
      name: "Capote",
      rank: "HE",
      img: "img/EGOs/meursault-capote-he.png",
      keywords: ["burn", "tremor", ],
      rarity: "EGO",
    },
    {
      id: "meursault-mircalla-waw",
      sinnerId: "meursault",
      name: "Yearning-Mircalla",
      rank: "WAW",
      img: "img/EGOs/meursault-mircalla-waw.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    {
      id: "meursault-crushbound-waw",
      sinnerId: "meursault",
      name: "Crushbound Past",
      rank: "WAW",
      img: "img/EGOs/meursault-crushbound-waw.png",
      keywords: ["tremor", ],
      rarity: "EGO",
    },
    // Add new Meursault EGOs here
  ],

  "hong-lu": [
    {
      id: "hong-lu-illusion-zayin",
      sinnerId: "hong-lu",
      name: "Land of Illusion",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/hong-lu-illusion-zayin.png",
      keywords: ["sinking", ],
      rarity: "EGO",
    },
    {
      id: "hong-lu-desire-teth",
      sinnerId: "hong-lu",
      name: "Roseate Desire",
      rank: "TETH",
      img: "img/EGOs/hong-lu-desire-teth.png",
      rarity: "EGO",
    },
    {
      id: "hong-lu-soda-teth",
      sinnerId: "hong-lu",
      name: "Soda",
      rank: "TETH",
      img: "img/EGOs/hong-lu-soda-teth.png",
      rarity: "EGO",
    },
    {
      id: "hong-lu-cavernous-teth",
      sinnerId: "hong-lu",
      name: "Cavernous Wailing",
      rank: "TETH",
      img: "img/EGOs/hong-lu-cavernous-teth.png",
      keywords: ["sinking", ],
      rarity: "EGO",
    },
    {
      id: "hong-lu-lasso-teth",
      sinnerId: "hong-lu",
      name: "Lasso",
      rank: "TETH",
      img: "img/EGOs/hong-lu-lasso-teth.png",
      keywords: ["bleed", "rupture", ],
      rarity: "EGO",
    },
    {
      id: "hong-lu-dimension-he",
      sinnerId: "hong-lu",
      name: "Dimension Shredder",
      rank: "HE",
      img: "img/EGOs/hong-lu-dimension-he.png",
      keywords: ["charge", ],
      rarity: "EGO",
    },
    {
      id: "hong-lu-effervescent-he",
      sinnerId: "hong-lu",
      name: "Effervescent Corrosion",
      rank: "HE",
      img: "img/EGOs/hong-lu-effervescent-he.png",
      keywords: ["rupture", ],
      rarity: "EGO",
    },
    {
      id: "hong-lu-oneself-he",
      sinnerId: "hong-lu",
      name: "To Remain Oneself",
      rank: "HE",
      img: "img/EGOs/hong-lu-oneself-he.png",
      keywords: ["sinking", "poise", ],
      rarity: "EGO",
    },
    {
      id: "hong-lu-tarnished-waw",
      sinnerId: "hong-lu",
      name: "Tears of the Tarnished Blood",
      rank: "WAW",
      img: "img/EGOs/hong-lu-tarnished-waw.png",
      rarity: "EGO",
    },
    // Add new Hong Lu EGOs here
  ],

  "heathcliff": [
    {
      id: "heathcliff-bodysack-zayin",
      sinnerId: "heathcliff",
      name: "Bodysack",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/heathcliff-bodysack-zayin.png",
      rarity: "EGO",
    },
    {
      id: "heathcliff-holiday-zayin",
      sinnerId: "heathcliff",
      name: "Holiday",
      rank: "ZAYIN",
      img: "img/EGOs/heathcliff-holiday-zayin.png",
      rarity: "EGO",
    },
    {
      id: "heathcliff-AEDD-teth",
      sinnerId: "heathcliff",
      name: "AEDD",
      rank: "TETH",
      img: "img/EGOs/heathcliff-AEDD-teth.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    {
      id: "heathcliff-fell-teth",
      sinnerId: "heathcliff",
      name: "Fell Bullet",
      rank: "TETH",
      img: "img/EGOs/heathcliff-fell-teth.png",
      keywords: ["bleed", "sinking", ],
      rarity: "EGO",
    },
    {
      id: "heathcliff-telepole-he",
      sinnerId: "heathcliff",
      name: "Telepole",
      rank: "HE",
      img: "img/EGOs/heathcliff-telepole-he.png",
      keywords: ["charge", ],
      rarity: "EGO",
    },
    {
      id: "heathcliff-ya-he",
      sinnerId: "heathcliff",
      name: "Ya Sunyata Tad Rupam",
      rank: "HE",
      img: "img/EGOs/heathcliff-ya-he.png",
      rarity: "EGO",
    },
    {
      id: "heathcliff-inertia-he",
      sinnerId: "heathcliff",
      name: "Asymmetrical Inertia",
      rank: "HE",
      img: "img/EGOs/heathcliff-inertia-he.png",
      keywords: ["tremor", ],
      rarity: "EGO",
    },
    {
      id: "heathcliff-binds-waw",
      sinnerId: "heathcliff",
      name: "Binds",
      rank: "WAW",
      img: "img/EGOs/heathcliff-binds-waw.png",
      keywords: ["tremor", "sinking", ],
      rarity: "EGO",
    },
    // Add new Heathcliff EGOs here
  ],

  "ishmael": [
    {
      id: "ishmael-snagharpoon-zayin",
      sinnerId: "ishmael",
      name: "Snagharpoon",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/ishmael-snagharpoon-zayin.png",
      keywords: ["tremor", ],
      rarity: "EGO",
    },
    {
      id: "ishmael-maggot-zayin",
      sinnerId: "ishmael",
      name: "Hundred-Footed Death Maggot",
      rank: "ZAYIN",
      img: "img/EGOs/ishmael-maggot-zayin.png",
      keywords: ["sinking", "rupture", ],
      rarity: "EGO",
    },
    {
      id: "ishmael-desire-teth",
      sinnerId: "ishmael",
      name: "Roseate Desire",
      rank: "TETH",
      img: "img/EGOs/ishmael-desire-teth.png",
      rarity: "EGO",
    },
    {
      id: "ishmael-capote-teth",
      sinnerId: "ishmael",
      name: "Capote",
      rank: "TETH",
      img: "img/EGOs/ishmael-capote-teth.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "ishmael-bygone-teth",
      sinnerId: "ishmael",
      name: "Bygone Days",
      rank: "TETH",
      img: "img/EGOs/ishmael-bygone-teth.png",
      keywords: ["sinking", ],
      rarity: "EGO",
    },
    {
      id: "ishmael-ardor-he",
      sinnerId: "ishmael",
      name: "Ardor Blossom Star",
      rank: "HE",
      img: "img/EGOs/ishmael-ardor-he.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "ishmael-wingbeat-he",
      sinnerId: "ishmael",
      name: "Wingbeat",
      rank: "HE",
      img: "img/EGOs/ishmael-wingbeat-he.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    {
      id: "ishmael-christmas-he",
      sinnerId: "ishmael",
      name: "Christmas Nightmare",
      rank: "HE",
      img: "img/EGOs/ishmael-christmas-he.png",
      keywords: ["tremor", "sinking", ],
      rarity: "EGO",
    },
    {
      id: "ishmael-tidal-he",
      sinnerId: "ishmael",
      name: "Tidal Elegy",
      rank: "HE",
      img: "img/EGOs/ishmael-tidal-he.png",
      keywords: ["tremor", "sinking", ],
      rarity: "EGO",
    },
    {
      id: "ishmael-obsession-waw",
      sinnerId: "ishmael",
      name: "Blind Obsession",
      rank: "WAW",
      img: "img/EGOs/ishmael-obsession-waw.png",
      keywords: ["poise", "charge", ],
      rarity: "EGO",
    },
    // Add new Ishmael EGOs here
  ],

  "rodion": [
    {
      id: "rodion-cast-zayin",
      sinnerId: "rodion",
      name: "What is Cast",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/rodion-cast-zayin.png",
      keywords: ["bleed", ],
      rarity: "EGO", 
    },
    {
      id: "rodion-rime-teth",
      sinnerId: "rodion",
      name: "Rime Shank",
      rank: "TETH",
      img: "img/EGOs/rodion-rime-teth.png",
      keywords: ["tremor", "sinking", ],
      rarity: "EGO",
    },
    {
      id: "rodion-effervescent-teth",
      sinnerId: "rodion",
      name: "Effervescent Corrosion",
      rank: "TETH",
      img: "img/EGOs/rodion-effervescent-teth.png",
      keywords: ["tremor", ],
      rarity: "EGO",
    },
    {
      id: "rodion-flame-he",
      sinnerId: "rodion",
      name: "4th Match Flame",
      rank: "HE",
      img: "img/EGOs/rodion-flame-he.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "rodion-pursuance-he",
      sinnerId: "rodion",
      name: "Pursuance",
      rank: "HE",
      img: "img/EGOs/rodion-pursuance-he.png",
      rarity: "EGO",
    },
    {
      id: "rodion-hex-he",
      sinnerId: "rodion",
      name: "Hex Nail",
      rank: "HE",
      img: "img/EGOs/rodion-hex-he.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    {
      id: "rodion-sanguine-waw",
      sinnerId: "rodion",
      name: "Sanguine Desire",
      rank: "WAW",
      img: "img/EGOs/rodion-sanguine-waw.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    {
      id: "rodion-indicants-waw",
      sinnerId: "rodion",
      name: "Indicant's Trial",
      rank: "WAW",
      img: "img/EGOs/rodion-indicants-waw.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    // Add new Rodion EGOs here
  ],

  "sinclair": [
    {
      id: "sinclair-branch-zayin",
      sinnerId: "sinclair",
      name: "Branch of Knowledge",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/sinclair-branch-zayin.png",
      keywords: ["rupture", ],
      rarity: "EGO",
    },
    {
      id: "sinclair-cavernous-zayin",
      sinnerId: "sinclair",
      name: "Cavernous Wailing",
      rank: "ZAYIN",
      img: "img/EGOs/sinclair-cavernous-zayin.png",
      rarity: "EGO",
    },
    {
      id: "sinclair-impending-teth",
      sinnerId: "sinclair",
      name: "Impending Day",
      rank: "TETH",
      img: "img/EGOs/sinclair-impending-teth.png",
      rarity: "EGO",
    },
    {
      id: "sinclair-stew-teth",
      sinnerId: "sinclair",
      name: "Lifetime Stew",
      rank: "TETH",
      img: "img/EGOs/sinclair-stew-teth.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "sinclair-hex-teth",
      sinnerId: "sinclair",
      name: "Hex Nail",
      rank: "TETH",
      img: "img/EGOs/sinclair-hex-teth.png",
      keywords: ["bleed", ],
      rarity: "EGO",
    },
    {
      id: "sinclair-lantern-he",
      sinnerId: "sinclair",
      name: "Lantern",
      rank: "HE",
      img: "img/EGOs/sinclair-lantern-he.png",
      keywords: ["rupture", ],
      rarity: "EGO",
    },
    {
      id: "sinclair-9:2-he",
      sinnerId: "sinclair",
      name: "9:2",
      rank: "HE",
      img: "img/EGOs/sinclair-9-2-he.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "sinclair-tarnished-waw",
      sinnerId: "sinclair",
      name: "Tears of the Tarnished Blood",
      rank: "WAW",
      img: "img/EGOs/sinclair-tarnished-waw.png",
      keywords: ["rupture", ],
      rarity: "EGO",
    },
    // Add new Sinclair EGOs here
  ],

  "outis": [
    {
      id: "outis-pathos-zayin",
      sinnerId: "outis",
      name: "To Pathos Mathos",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/outis-pathos-zayin.png",
      keywords: ["rupture", ],
      rarity: "EGO",
    },
    {
      id: "outis-ya-teth",
      sinnerId: "outis",
      name: "Ya Sunyata Tad Rupam",
      rank: "TETH",
      img: "img/EGOs/outis-ya-teth.png",
      rarity: "EGO",
    },
    {
      id: "outis-sunshower-teth",
      sinnerId: "outis",
      name: "Sunshower",
      rank: "TETH",
      img: "img/EGOs/outis-sunshower-teth.png",
      keywords: ["tremor", "sinking", ],
      rarity: "EGO",
    },
    {
      id: "outis-ebony-he",
      sinnerId: "outis",
      name: "Ebony Stem",
      rank: "HE",
      img: "img/EGOs/outis-ebony-he.png",
      keywords: ["bleed", "rupture", ],
      rarity: "EGO",
    },
    {
      id: "outis-holiday-he",
      sinnerId: "outis",
      name: "Holiday",
      rank: "HE",
      img: "img/EGOs/outis-holiday-he.png",
      keywords: ["tremor", ],
      rarity: "EGO",
    },
    {
      id: "outis-dimension-he",
      sinnerId: "outis",
      name: "Dimension Shredder",
      rank: "HE",
      img: "img/EGOs/outis-dimension-he.png",
      keywords: ["charge", ],
      rarity: "EGO",
    },
    {
      id: "outis-magic-he",
      sinnerId: "outis",
      name: "Magic Bullet",
      rank: "HE",
      img: "img/EGOs/outis-magic-he.png",
      keywords: ["burn", ],
      rarity: "EGO",
    },
    {
      id: "outis-binds-waw",
      sinnerId: "outis",
      name: "Binds",
      rank: "WAW",
      img: "img/EGOs/outis-binds-waw.png",
      keywords: ["tremor", ],
      rarity: "EGO",
    },
    // Add new Outis EGOs here
  ],

  "gregor": [
    {
      id: "gregor-suddenly-zayin",
      sinnerId: "gregor",
      name: "Suddenly, One Day",
      rank: "ZAYIN",
      isBase: true,
      img: "img/EGOs/gregor-suddenly-zayin.png",
      rarity: "EGO",
    },
    {
      id: "gregor-legerdemain-zayin",
      sinnerId: "gregor",
      name: "Legerdemain",
      rank: "ZAYIN",
      img: "img/EGOs/gregor-legerdemain-zayin.png",
      keywords: ["tremor", ],
      rarity: "EGO",
    },
    {
      id: "gregor-lantern-teth",
      sinnerId: "gregor",
      name: "Lantern",
      rank: "TETH",
      img: "img/EGOs/gregor-lantern-teth.png",
      rarity: "EGO",
    },
    {
      id: "gregor-bygone-teth",
      sinnerId: "gregor",
      name: "Bygone Days",
      rank: "TETH",
      img: "img/EGOs/gregor-bygone-teth.png",
      keywords: ["sinking", ],
      rarity: "EGO",
    },
    {
      id: "gregor-AEDD-he",
      sinnerId: "gregor",
      name: "AEDD",
      rank: "HE",
      img: "img/EGOs/gregor-AEDD-he.png",
      keywords: ["charge", ],
      rarity: "EGO",
    },
    {
      id: "gregor-solemn-he",
      sinnerId: "gregor",
      name: "Solemn Lament",
      rank: "HE",
      img: "img/EGOs/gregor-solemn-he.png",
      rarity: "EGO",
    },
    {
      id: "gregor-christmas-he",
      sinnerId: "gregor",
      name: "Christmas Nightmare",
      rank: "HE",
      img: "img/EGOs/gregor-christmas-he.png",
      keywords: ["tremor", "sinking", ],
      rarity: "EGO",
    },
    {
      id: "gregor-garden-waw",
      sinnerId: "gregor",
      name: "Garden of Thorns",
      rank: "WAW",
      img: "img/EGOs/gregor-garden-waw.png",
      rarity: "EGO",
    },
    {
      id: "gregor-unbrilliant-waw",
      sinnerId: "gregor",
      name: "Unbrilliant Glory",
      rank: "WAW",
      img: "img/EGOs/gregor-unbrilliant-waw.png",
      keywords: ["burn", "tremor", ],
      rarity: "EGO",
    },
    // Add new Gregor EGOs here
  ]
};

// after defining sinnerIdentities and sinnerEgos, define flattened arrays and shard cost map
export const allIdentities = Object.values(sinnerIdentities).flat();
export const allEgos = Object.values(sinnerEgos).flat();

export const shardCostByRarity = {
  base: 0,
  "000": costPer000,
  "00": costPer00,
  EGO: costPer000, // all EGOs cost 400
};
